spring.application.name=order-service
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3309/orderdb
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.LongSerializer

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
