version: '3'

services:

  nginx:
    container_name: api-gateway
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - topics
      - words
    networks:
      - stavya-para-paroktih

  frontend:
    container_name: frontend
    expose:
      - "3002"
    build:
      context: ./frontend
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - TOPIC_BACKEND_BASE_URL=http://localhost
      - WORD_BACKEND_BASE_URL=http://localhost
    depends_on:
      - topics
      - words
    networks:
      stavya-para-paroktih:
        aliases:
          - frontend

  topics:
    container_name: topics
    expose:
      - "3000"
    build:
      context: ./backend/topic
    environment:
      - PORT=3000
      - FRONTEND_SERVICE_URL=http://frontend:3002
    networks:
      stavya-para-paroktih:
        aliases:
          - topics
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  words:
    container_name: words
    expose:
      - "3001"
    build:
      context: ./backend/word
    environment:
      - PORT=3001
      - FRONTEND_SERVICE_URL=http://frontend:3002
    networks:
      stavya-para-paroktih:
        aliases:
          - words
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  stavya-para-paroktih:
    driver: bridge
