version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network
    depends_on:
      - topics
      - words

  topics:
    build: ./backend/topic
    networks:
      - my_network

  words:
    build: ./backend/word
    networks:
      - my_network

  frontend:
    build: ./frontend
    ports:
      - "3002:3002"
    environment:
      - PORT= 3002
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
