version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - topics
      - words

  topics:
    build: ./backend/topic
    ports:
      - "3000:3000"

  words:
    build: ./backend/word
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    ports:
      - "3002:3002"
    environment:
      - PORT= 3002
