services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    command: start-dev --import-realm
    ports:
      - "8089:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
