import{useEffect,useState}from'react';import axios from'axios';import{Alert,Box,Button,Card,CardContent,Checkbox,Chip,CircularProgress,Container,Dialog,DialogActions,DialogContent,DialogTitle,Grid,LinearProgress,Paper,Stack,Table,TableBody,TableCell,TableContainer,TableHead,TablePagination,TableRow,TextField,Typography}from'@mui/material';import SearchIcon from'@mui/icons-material/Search';import StopIcon from'@mui/icons-material/Stop';import DeleteIcon from'@mui/icons-material/Delete';import DriveFileMoveIcon from'@mui/icons-material/DriveFileMove';import FolderOpenIcon from'@mui/icons-material/FolderOpen';
const API=import.meta.env.VITE_API_BASE_URL||'http://localhost:8080/api';const fmt=b=>{if(b<1024)return b+' B';let u=['KB','MB','GB','TB'],i=-1,v=b;do{v/=1024;i++}while(v>=1024&&i<u.length-1);return v.toFixed(v>=100?0:2)+' '+u[i]};
export default function App(){const[path,setPath]=useState(''),[ignored,setIgnored]=useState(['.git','node_modules','.idea']),[ignoreInput,setIgnoreInput]=useState(''),[job,setJob]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[groups,setGroups]=useState([]),[total,setTotal]=useState(0),[page,setPage]=useState(0),[rows,setRows]=useState(10),[sort,setSort]=useState('wastedBytes'),[dir,setDir]=useState('desc'),[selected,setSelected]=useState([]),[folder,setFolder]=useState(''),[entries,setEntries]=useState([]),[moveOpen,setMoveOpen]=useState(false),[target,setTarget]=useState('');
const loadGroups=async()=>{if(!job?.id)return;try{let r=await axios.get(`${API}/duplicates/scan/${job.id}/groups`,{params:{page,size:rows,sortBy:sort,direction:dir}});setGroups(r.data.content);setTotal(r.data.totalElements)}catch(e){setError(e.response?.data?.error||e.message)}};
useEffect(()=>{if(job?.status==='COMPLETED')loadGroups()},[job?.status,page,rows,sort,dir]);
const start=async()=>{if(!path.trim())return setError('Enter a folder path.');setError('');setBusy(true);setSelected([]);setPage(0);try{let r=await axios.post(`${API}/duplicates/scan`,{rootPath:path.trim(),ignoredFolders:ignored});setJob({id:r.data.jobId,status:'QUEUED',percent:0});let es=new EventSource(`${API}/duplicates/scan/${r.data.jobId}/events`);es.addEventListener('progress',e=>{let d=JSON.parse(e.data);setJob(d);if(['COMPLETED','FAILED','CANCELLED'].includes(d.status)){es.close();setBusy(false)}});es.onerror=()=>{es.close();setBusy(false)}}catch(e){setError(e.response?.data?.error||e.message);setBusy(false)}};
const cancel=async()=>{if(job?.id)await axios.post(`${API}/duplicates/scan/${job.id}/cancel`)};const addIgnore=()=>{let x=ignoreInput.split(',').map(s=>s.trim().toLowerCase()).filter(Boolean);setIgnored(a=>[...new Set([...a,...x])]);setIgnoreInput('')};const toggle=p=>setSelected(a=>a.includes(p)?a.filter(x=>x!==p):[...a,p]);
const remove=async()=>{if(!selected.length||!confirm(`Delete ${selected.length} file(s)?`))return;try{await axios.delete(`${API}/files`,{data:{paths:selected}});setSelected([]);loadGroups()}catch(e){setError(e.response?.data?.error||e.message)}};
const move=async()=>{try{await axios.post(`${API}/files/move`,{paths:selected,targetDirectory:target});setSelected([]);setMoveOpen(false);setTarget('');loadGroups()}catch(e){setError(e.response?.data?.error||e.message)}};
const browse=async()=>{try{let r=await axios.get(`${API}/files/browse`,{params:{path:folder}});setEntries(r.data)}catch(e){setError(e.response?.data?.error||e.message)}};
const changeSort=k=>{setDir(sort===k&&dir==='desc'?'asc':'desc');setSort(k);setPage(0)};
return <Container maxWidth="xl" sx={{py:3}}><Stack spacing={2.5}><Box><Typography variant="h4" fontWeight={800}>Duplicate File Finder v4</Typography><Typography color="text.secondary">SSE progress · persistent jobs · server pagination · safe file operations</Typography></Box>
<Paper sx={{p:2.5}}><Stack direction={{xs:'column',md:'row'}} spacing={1.5}><TextField fullWidth label="Root folder" value={path} onChange={e=>setPath(e.target.value)}/><Button variant="contained" disabled={busy} onClick={start} startIcon={busy?<CircularProgress size={18} color="inherit"/>:<SearchIcon/>}>Scan</Button><Button variant="outlined" color="error" disabled={!busy} onClick={cancel} startIcon={<StopIcon/>}>Cancel</Button></Stack>
<Typography fontWeight={700} sx={{mt:2}}>Ignored folders</Typography><Stack direction={{xs:'column',md:'row'}} spacing={1} sx={{mt:1}}><TextField size="small" fullWidth label="Add names, comma separated" value={ignoreInput} onChange={e=>setIgnoreInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addIgnore()}/><Button variant="outlined" onClick={addIgnore}>Add</Button></Stack><Stack direction="row" spacing={1} sx={{mt:1,flexWrap:'wrap'}}>{ignored.map(x=><Chip key={x} label={x} onDelete={()=>setIgnored(a=>a.filter(v=>v!==x))} sx={{mb:.5}}/>)}</Stack>
{job&&<Box sx={{mt:2}}><LinearProgress variant="determinate" value={job.percent||0}/><Typography variant="caption">{job.message||job.status} · {job.percent||0}%</Typography></Box>}</Paper>
{error&&<Alert severity="error" onClose={()=>setError('')}>{error}</Alert>}
{job&&<Grid container spacing={1.5}>{[['Status',job.status],['Groups',job.duplicateGroups||0],['Duplicate files',job.duplicateFiles||0],['Wasted',fmt(job.wastedBytes||0)]].map(([a,b])=><Grid key={a} size={{xs:6,md:3}}><Card><CardContent><Typography color="text.secondary">{a}</Typography><Typography variant="h5" fontWeight={800}>{b}</Typography></CardContent></Card></Grid>)}</Grid>}
{job?.status==='COMPLETED'&&<Stack direction="row" spacing={1}><Button color="error" variant="contained" disabled={!selected.length} startIcon={<DeleteIcon/>} onClick={remove}>Delete selected ({selected.length})</Button><Button variant="outlined" disabled={!selected.length} startIcon={<DriveFileMoveIcon/>} onClick={()=>setMoveOpen(true)}>Move selected</Button></Stack>}
{job?.status==='COMPLETED'&&<Paper><TableContainer><Table><TableHead><TableRow><TableCell>Group</TableCell><TableCell onClick={()=>changeSort('fileSize')} className="sortable">Size</TableCell><TableCell onClick={()=>changeSort('wastedBytes')} className="sortable">Wasted</TableCell><TableCell>SHA-256</TableCell><TableCell>Files</TableCell></TableRow></TableHead><TableBody>{groups.map(g=><TableRow key={g.groupNumber}><TableCell>#{g.groupNumber}</TableCell><TableCell>{fmt(g.fileSize)}</TableCell><TableCell>{fmt(g.wastedBytes)}</TableCell><TableCell className="hash">{g.sha256}</TableCell><TableCell>{g.files.map(f=><Stack direction="row" alignItems="center" key={f.path}><Checkbox size="small" checked={selected.includes(f.path)} onChange={()=>toggle(f.path)}/><Typography variant="body2" className="path">{f.path}</Typography></Stack>)}</TableCell></TableRow>)}</TableBody></Table></TableContainer><TablePagination component="div" count={total} page={page} rowsPerPage={rows} onPageChange={(_,p)=>setPage(p)} onRowsPerPageChange={e=>{setRows(+e.target.value);setPage(0)}}/></Paper>}
<Paper sx={{p:2}}><Typography variant="h6" fontWeight={700}>Folder Browser</Typography><Stack direction={{xs:'column',md:'row'}} spacing={1} sx={{mt:1}}><TextField fullWidth size="small" label="Folder path" value={folder} onChange={e=>setFolder(e.target.value)}/><Button variant="outlined" onClick={browse}>Open</Button></Stack><Stack direction="row" spacing={1} sx={{mt:1,flexWrap:'wrap'}}>{entries.map(e=><Button key={e.path} size="small" startIcon={e.directory?<FolderOpenIcon/>:undefined} onDoubleClick={()=>e.directory&&(setFolder(e.path),setTimeout(browse,0))}>{e.name}{e.directory?' /':` (${fmt(e.size)})`}</Button>)}</Stack></Paper></Stack>
<Dialog open={moveOpen} onClose={()=>setMoveOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Move selected files</DialogTitle><DialogContent><TextField autoFocus fullWidth sx={{mt:1}} label="Target directory" value={target} onChange={e=>setTarget(e.target.value)}/></DialogContent><DialogActions><Button onClick={()=>setMoveOpen(false)}>Cancel</Button><Button variant="contained" onClick={move}>Move</Button></DialogActions></Dialog></Container> }
