const LOADING_FETCH_NODE_LIST = "consolidated-report/FETCH_NODE_LIST/LOADING";
const SUCCESS_FETCH_NODE_LIST = "consolidated-report/FETCH_NODE_LIST/SUCCESS";
const ERROR_FETCH_NODE_LIST = "consolidated-report/FETCH_NODE_LIST/ERROR";

const LOADING_FETCH_SELECTED_NODE_DETAILS = "consolidated-report/FETCH_SELECTED_NODE_DETAILS/LOADING";
const SUCCESS_FETCH_SELECTED_NODE_DETAILS = "consolidated-report/FETCH_SELECTED_NODE_DETAILS/SUCCESS";
const ERROR_FETCH_SELECTED_NODE_DETAILS = "consolidated-report/FETCH_SELECTED_NODE_DETAILS/ERROR";

export {
  LOADING_FETCH_NODE_LIST,
  SUCCESS_FETCH_NODE_LIST,
  ERROR_FETCH_NODE_LIST,
  LOADING_FETCH_SELECTED_NODE_DETAILS,
  SUCCESS_FETCH_SELECTED_NODE_DETAILS,
  ERROR_FETCH_SELECTED_NODE_DETAILS,
};
