const SHOW_BACKDROP_V1 = "backdrop/v1/SHOW_BACKDROP";
const HIDE_BACKDROP_V1 = "backdrop/v1/HIDE_BACKDROP";

const SHOW_BACKDROP_V3 = "backdrop/v1/SHOW_BACKDROP_V3";
const HIDE_BACKDROP_V3 = "backdrop/v1/HIDE_BACKDROP_V3";
const UPDATE_BACKDROP_V3 = "backdrop/v1/UPDATE_BACKDROP_V3";

export { SHOW_BACKDROP_V1, HIDE_BACKDROP_V1, SHOW_BACKDROP_V3, HIDE_BACKDROP_V3, UPDATE_BACKDROP_V3 };
