package com.prem.duplicatefinder.service;
import com.prem.duplicatefinder.model.*;import org.springframework.stereotype.Service;import java.nio.file.*;import java.util.*;
@Service public class FileOperationService{
 public List<FolderEntry> browse(String v)throws Exception{Path r=norm(v);if(!Files.isDirectory(r))throw new IllegalArgumentException("Not a directory: "+r);try(var s=Files.list(r)){return s.sorted(Comparator.comparing((Path p)->!Files.isDirectory(p)).thenComparing(p->p.getFileName().toString().toLowerCase())).map(p->{try{return new FolderEntry(p.getFileName().toString(),p.toString(),Files.isDirectory(p),Files.isDirectory(p)?0:Files.size(p));}catch(Exception e){return new FolderEntry(p.getFileName().toString(),p.toString(),Files.isDirectory(p),0);}}).toList();}}
 public OperationResult delete(List<String> ps){int ok=0;List<String>e=new ArrayList<>();for(String v:safe(ps))try{Path p=norm(v);if(Files.isDirectory(p))throw new IllegalArgumentException("Directory deletion is disabled");if(Files.deleteIfExists(p))ok++;}catch(Exception x){e.add(v+": "+x.getMessage());}return new OperationResult(ok,e);}
 public OperationResult move(List<String>ps,String dir){int ok=0;List<String>e=new ArrayList<>();try{Path d=norm(dir);Files.createDirectories(d);if(!Files.isDirectory(d))throw new IllegalArgumentException("Target is not a directory");for(String v:safe(ps))try{Path p=norm(v);if(Files.isDirectory(p))throw new IllegalArgumentException("Directory move is disabled");Path t=unique(d.resolve(p.getFileName()));try{Files.move(p,t,StandardCopyOption.ATOMIC_MOVE);}catch(AtomicMoveNotSupportedException z){Files.move(p,t);}ok++;}catch(Exception x){e.add(v+": "+x.getMessage());}}catch(Exception x){e.add("Target directory: "+x.getMessage());}return new OperationResult(ok,e);}
 private List<String>safe(List<String>p){return p==null?List.of():p.stream().filter(Objects::nonNull).filter(x->!x.isBlank()).distinct().limit(500).toList();}
 private Path norm(String x){if(x==null||x.isBlank())throw new IllegalArgumentException("Path is required");return Paths.get(x).toAbsolutePath().normalize();}
 private Path unique(Path t){if(!Files.exists(t))return t;String n=t.getFileName().toString(),b=n,e="";int d=n.lastIndexOf('.');if(d>0){b=n.substring(0,d);e=n.substring(d);}for(int i=1;i<100000;i++){Path x=t.resolveSibling(b+" ("+i+")"+e);if(!Files.exists(x))return x;}throw new IllegalStateException("Unique target unavailable");}
}
