services:
  redis:
    image: redis:7-alpine
    container_name: todo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.4
    container_name: todo-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - todo_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
volumes:
  todo_mysql_data:
