#spring.application.name=api-gateway
spring:
  application:
    name: "gatewayserver"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

server:
  port: 8072

# Service discovery related configuration
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

jwt:
  secret: your_jwt_secret_key
  expiration: 3600000

custom:
  prem:
    validation-url: http://loginapp:8089/auth-service/validate
    open-api-endpoints:
      - /api/auth/login
      - /api/auth/token
      - /api/auth/validate
#      - /actuator/
      - /eureka/