# Server Configuration
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/ex_base_18_directory_topic_db
spring.data.mongodb.auto-index-creation=true

# Logging
logging.level.com.p.backend=INFO
logging.level.org.springframework.data.mongodb=DEBUG

# OpenAPI/Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Application
spring.application.name=directory-topic-management-api

