services:
  mongodb:
    image: mongo:8
    container_name: mini-gmail-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mini-gmail-data:/data/db

volumes:
  mini-gmail-data:
