services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    container_name: oauth2-keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
