import React,{useEffect,useState} from 'react'; import api from './api/http'; import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
function Login({onLogin}){const [u,setU]=useState('demo'),[p,setP]=useState('password'),[reg,setReg]=useState(false),[err,setErr]=useState('');
 const submit=async e=>{e.preventDefault();setErr('');try{if(reg)await api.post('/auth/register',{username:u,password:p});const r=await api.post('/auth/login',{username:u,password:p});localStorage.setItem('accessToken',r.data.accessToken);localStorage.setItem('refreshToken',r.data.refreshToken);onLogin()}catch(x){setErr(x.response?.data?.message||'Request failed')}};
 return <div className="card auth"><h1>Todo App</h1><form onSubmit={submit}><input placeholder="Username" value={u} onChange={e=>setU(e.target.value)}/><input type="password" placeholder="Password" value={p} onChange={e=>setP(e.target.value)}/><button>{reg?'Register & Login':'Login'}</button></form><button className="link" onClick={()=>setReg(!reg)}>{reg?'Existing user? Login':'Create account'}</button>{err&&<p className="error">{err}</p>}<small>Demo: demo/password · Admin: admin/admin123</small></div>}
function TodoApp({onLogout}){const qc=useQueryClient(),[search,setSearch]=useState(''),[completed,setCompleted]=useState(''),[page,setPage]=useState(0),[title,setTitle]=useState('');const filters={page,size:5,search,completed:completed===''?undefined:completed};
 const q=useQuery({queryKey:['todos',filters],queryFn:()=>api.get('/todos',{params:filters}).then(r=>r.data),placeholderData:x=>x});
 const add=useMutation({mutationFn:t=>api.post('/todos',{title:t,description:'',completed:false}),onSuccess:()=>{setTitle('');qc.invalidateQueries({queryKey:['todos']})}});
 const toggle=useMutation({mutationFn:id=>api.patch('/todos/'+id+'/complete'),onSuccess:()=>qc.invalidateQueries({queryKey:['todos']})});
 const del=useMutation({mutationFn:id=>api.delete('/todos/'+id),onSuccess:()=>qc.invalidateQueries({queryKey:['todos']})});
 return <div className="page"><header><h1>Todos</h1><button onClick={onLogout}>Logout</button></header><div className="toolbar"><input placeholder="Search..." value={search} onChange={e=>{setPage(0);setSearch(e.target.value)}}/><select value={completed} onChange={e=>{setPage(0);setCompleted(e.target.value)}}><option value="">All</option><option value="true">Completed</option><option value="false">Pending</option></select></div><form className="add" onSubmit={e=>{e.preventDefault();if(title.trim())add.mutate(title.trim())}}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="New todo"/><button>Add</button></form><div>{q.isLoading?'Loading...':q.data?.content.map(t=><div className="todo" key={t.id}><span className={t.completed?'done':''}>{t.title}</span><button onClick={()=>toggle.mutate(t.id)}>{t.completed?'Undo':'Done'}</button><button onClick={()=>del.mutate(t.id)}>Delete</button></div>)}</div><footer><button disabled={!q.data?.first} onClick={()=>setPage(page-1)}>Prev</button><span> Page {page+1} / {q.data?.totalPages||1} </span><button disabled={!q.data?.last} onClick={()=>setPage(page+1)}>Next</button></footer></div>}
function App(){const [auth,setAuth]=useState(!!localStorage.getItem('accessToken'));useEffect(()=>{const f=()=>setAuth(false);addEventListener('auth-expired',f);return()=>removeEventListener('auth-expired',f)},[]);if(!auth)return <Login onLogin={()=>setAuth(true)}/>;return <TodoApp onLogout={async()=>{try{await api.post('/auth/logout',null,{params:{token:localStorage.getItem('refreshToken')}})}finally{localStorage.clear();setAuth(false)}}}/>}; export default App;
