const TOGGLE_VIEW_MODE = "application-states/TOGGLE_VIEW_MODE";
const SET_SELECTED_MODULE_NAME = "application-states/SET_SELECTED_MODULE_NAME";

const COLLAPSE_SIDE_BAR = "application-states/COLLAPSE_SIDE_BAR";
const EXPAND_SIDE_BAR = "application-states/EXPAND_SIDE_BAR";

export { TOGGLE_VIEW_MODE, SET_SELECTED_MODULE_NAME, COLLAPSE_SIDE_BAR, EXPAND_SIDE_BAR };
