apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-hello-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-hello
  template:
    metadata:
      labels:
        app: spring-hello
    spec:
      containers:
        - name: spring-hello
          image: sameer426/spring-hello:21      # local image tag
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: spring-hello-service
spec:
  type: NodePort
  selector:
    app: spring-hello
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
