import { calculateNextPrev } from "../../common/utils/utility-methods";

const questionData0 = [
  {
    sectionId: "section_1",
    subSectionId: "sub_sec_1_1",
    id: "ques_1_1_1",
    name: "What are the differences between let, const, and var in terms of scope and reassignability?",
    answerFiles: [
      "17Jan2025.javascript--es6-concepts--what-are-the-differences-between-let-const-and-var-in-terms-of-scope-and-reassignability.md",
    ],
  },
  {
    sectionId: "section_1",
    subSectionId: "sub_sec_1_1",
    id: "ques_1_1_2",
    name: "How do arrow functions differ from regular functions in terms of syntax, this binding, and usage?",

    answerFiles: [
      "17Jan2025.javascript--es6-concepts--how-do-arrow-functions-differ-from-regular-functions-in-terms-of-syntax-this-binding-and-usage.md",
    ],
  },
  {
    sectionId: "section_1",
    subSectionId: "sub_sec_1_1",
    id: "ques_1_1_3",
    name: "Give an example of using .map() to transform an array.",

    answerFiles: [
      "17Jan2025.javascript--es6-concepts--give-an-example-of-using-map-to-transform-an-array.md",
    ],
  },
  {
    sectionId: "section_1",
    subSectionId: "sub_sec_1_1",
    id: "ques_1_1_4",
    name: "When would you use .reduce() instead of .forEach()? Provide an example.",

    answerFiles: [
      "17Jan2025.javascript--es6-concepts--when-would-you-use-reduce-instead-of-foreach-provide-an-example.md",
    ],
  },
  {
    sectionId: "section_1",
    subSectionId: "sub_sec_1_1",
    id: "ques_1_1_5",
    name: "Explain the differences between .filter() and .map() with a practical use case.",
    answerFiles: [
      "17Jan2025.javascript--es6-concepts--explain-the-differences-between-filter-and-map-with-a-practical-use-case.md",
    ],
  },
  {
    sectionId: "section_1",
    subSectionId: "sub_sec_1_2",
    id: "ques_1_2_1",
    name: "Why is JavaScript called a single-threaded language, and how does the event loop manage asynchronous tasks?",

    answerFiles: [
      "17Jan2025.javascript--event-loop--why-is-javascript-called-a-singlethreaded-language-and-how-does-the-event-loop-manage-asynchronous-tasks.md",
    ],
    links: [
      {
        title: "JavaScript Visualized - Event Loop, Web APIs, (Micro)task Queue",
        link: "https://www.youtube.com/watch?v=eiC58R16hb8",
      },
    ],
  },
  {
    sectionId: "section_1",
    subSectionId: "sub_sec_1_2",
    id: "ques_1_2_2",
    name: "Explain the difference between callbacks, Promises, and async/await in JavaScript. Provide examples.",
    answerFiles: [
      "17Jan2025.javascript--event-loop--explain-the-difference-between-callbacks-promises-and-asyncawait-in-javascript-provide-examples.md",
    ],
  },
  {
    sectionId: "section_1",
    subSectionId: "sub_sec_1_3",
    id: "ques_1_3_1",
    name: "Describe the event loop and how it manages the call stack and web APIs.",
    answerFiles: [
      "17Jan2025.javascript--event-loop--describe-the-event-loop-and-how-it-manages-the-call-stack-and-web-apis.md",
    ],
  },
  {
    sectionId: "section_1",
    subSectionId: "sub_sec_1_3",
    id: "ques_1_3_2",
    name: "Write a code snippet to fetch data from an API using both fetch and Axios.",

    answerFiles: [
      "17Jan2025.javascript--asynchronous-programming--write-a-code-snippet-to-fetch-data-from-an-api-using-both-fetch-and-axios.md",
    ],
  },
  {
    sectionId: "section_1",
    subSectionId: "sub_sec_1_3",
    id: "ques_1_3_3",
    name: "How can you handle errors in an async function using try/catch? Provide an example.",

    answerFiles: [
      "17Jan2025.javascript--asynchronous-programming--how-can-you-handle-errors-in-an-async-function-using-trycatch-provide-an-example.md",
    ],
  },
  {
    sectionId: "section_1",
    subSectionId: "sub_sec_1_4",
    id: "ques_1_4_1",
    name: "What are the key points to consider when conducting a peer code review?",
    answerFiles: [
      "17Jan2025.peer-code-review--what-are-the-key-points-to-consider-when-conducting-a-peer-code-review.md",
    ],
  },
  {
    sectionId: "section_1",
    subSectionId: "sub_sec_1_4",
    id: "ques_1_4_2",
    name: "How can constructive feedback improve code quality during a code review?",
    answerFiles: [
      "17Jan2025.peer-code-review--how-can-constructive-feedback-improve-code-quality-during-a-code-review.md",
    ],
  },
  {
    sectionId: "section_2",
    subSectionId: "sub_sec_2_1",
    id: "ques_2_1_1",
    name: "What are the key differences between functional components and class components?",
    answerFiles: ["17Jan2025.reactjs--basics--key-differences-between-functional-and-class-components.md"],
  },
  {
    sectionId: "section_2",
    subSectionId: "sub_sec_2_1",
    id: "ques_2_1_2",
    name: "Explain the usage of useState and useEffect hooks with examples.",
    answerFiles: ["17Jan2025.reactjs--basics--usage-of-usestate-and-useeffect-hooks-with-examples.md"],
  },
  {
    sectionId: "section_2",
    subSectionId: "sub_sec_2_1",
    id: "ques_2_1_3",
    name: "How can you optimize performance in React using React.memo?",
    answerFiles: ["17Jan2025.reactjs--basics--process-to-optimize-performance-in-react-using-reactmemo.md"],
  },
  {
    sectionId: "section_2",
    subSectionId: "sub_sec_2_1",
    id: "ques_2_1_4",
    name: "What are the differences between useMemo and useCallback? Provide examples.",
    answerFiles: ["17Jan2025.reactjs--basics--differences-between-usememo-and-usecallback--with-examples.md"],
  },
  {
    sectionId: "section_2",
    subSectionId: "sub_sec_2_2",
    id: "ques_2_2_1",
    name: "Describe the role of reducers and actions in Redux.",
    answerFiles: ["17Jan2025.reactjs--redux-and-state-management--role-of-reducers-and-actions-in-redux.md"],
  },
  {
    sectionId: "section_2",
    subSectionId: "sub_sec_2_2",
    id: "ques_2_2_2",
    name: "How would you integrate Redux with React? Write an example using useSelector and useDispatch.",
    answerFiles: [
      "17Jan2025.reactjs--redux-and-state-management--integration-of-redux-with-react--with-example-using-useselector-and-usedispatch.md",
    ],
  },
  {
    sectionId: "section_2",
    subSectionId: "sub_sec_2_2",
    id: "ques_2_2_3",
    name: "Compare Context API and Redux. When would you prefer one over the other?",
    answerFiles: [
      "17Jan2025.reactjs--redux-and-state-management--context-api-and-redux--preference-criteria-to-use-them.md",
    ],
  },
  {
    sectionId: "section_2",
    subSectionId: "sub_sec_2_3",
    id: "ques_2_3_1",
    name: "How does the CSS Box Model work? Provide an example.",
    answerFiles: ["17Jan2025.reactjs--css-in-react--how-does-the-css-box-model-work--provide-an-example.md"],
  },
  {
    sectionId: "section_2",
    subSectionId: "sub_sec_2_3",
    id: "ques_2_3_2",
    name: "What are the advantages of using Styled-Components or Material UI in React applications?",
    answerFiles: [
      "17Jan2025.reactjs--css-in-react--advantages-of-using-styledcomponents-or-material-ui-or-tailwindcss.md",
    ],
  },
  {
    sectionId: "section_3",
    subSectionId: "sub_sec_3_1",
    id: "ques_3_1_1",
    name: "What are lambda expressions, and how do they differ from anonymous classes?",
    answerFiles: [
      "16Jan2025.java--what-are-lambda-expressions-and-how-do-they-differ-from-anonymous-classes.md",
    ],
  },
  {
    sectionId: "section_3",
    subSectionId: "sub_sec_3_1",
    id: "ques_3_1_2",
    name: "Explain the Stream API and provide an example of filtering and sorting a collection.",
    answerFiles: [
      "16Jan2025.java--explain-the-stream-api-and-provide-an-example-of-filtering-and-sorting-a-collection.md",
    ],
  },
  {
    sectionId: "section_3",
    subSectionId: "sub_sec_3_1",
    id: "ques_3_1_3",
    name: "How would you create and handle a custom exception in Java?",
    answerFiles: ["16Jan2025.java--how-would-you-create-and-handle-a-custom-exception-in-java.md"],
  },
  {
    sectionId: "section_3",
    subSectionId: "sub_sec_3_1",
    id: "ques_3_1_4",
    name: "Compare ArrayList and LinkedList in terms of usage and performance.",
    answerFiles: ["16Jan2025.java--compare-arraylist-and-linkedlist-in-terms-of-usage-and-performance.md"],
  },
  {
    sectionId: "section_3",
    subSectionId: "sub_sec_3_2",
    id: "ques_3_2_1",
    name: "Write a sample @RestController with @GetMapping and @PostMapping.",
    answerFiles: ["16Jan2025.java--write-a-sample-restcontroller-with-getmapping-and-postmapping.md"],
  },
  {
    sectionId: "section_3",
    subSectionId: "sub_sec_3_2",
    id: "ques_3_2_2",
    name: "How do you implement JWT for authentication and authorization in Spring Boot?",
    answerFiles: [
      "16Jan2025.java--how-do-you-implement-jwt-for-authentication-and-authorization-in-spring-boot.md",
    ],
  },
  {
    sectionId: "section_3",
    subSectionId: "sub_sec_3_2",
    id: "ques_3_2_3",
    name: "What is the purpose of @ControllerAdvice in Spring Boot applications?",
    answerFiles: ["16Jan2025.java--what-is-the-purpose-of-controlleradvice-in-spring-boot-applications.md"],
  },
  {
    sectionId: "section_3",
    subSectionId: "sub_sec_3_3",
    id: "ques_3_3_1",
    name: "Explain the key differences between OAuth2 and JWT for securing APIs.",
    answerFiles: ["16Jan2025.java--explain-the-key-differences-between-oauth2-and-jwt-for-securing-apis.md"],
  },
  {
    sectionId: "section_3",
    subSectionId: "sub_sec_3_3",
    id: "ques_3_3_2",
    name: "How is a RestController different from a Controller in Spring Boot?",
    answerFiles: ["16Jan2025.java--how-is-a-restcontroller-different-from-a-controller-in-spring-boot.md"],
  },
  {
    sectionId: "section_3",
    subSectionId: "sub_sec_3_4",
    id: "ques_3_4_1",
    name: "Compare the Criteria API and HQL with examples.",
    answerFiles: ["16Jan2025.java--compare-the-criteria-api-and-hql-with-examples.md"],
  },
  {
    sectionId: "section_3",
    subSectionId: "sub_sec_3_4",
    id: "ques_3_4_2",
    name: "What is the difference between lazy and eager loading in Hibernate? Provide examples.",
    answerFiles: [
      "16Jan2025.java--what-is-the-difference-between-lazy-and-eager-loading-in-hibernate-provide-examples.md",
    ],
  },
  {
    sectionId: "section_3",
    subSectionId: "sub_sec_3_5",
    id: "ques_3_5_1",
    name: "What is the difference between Callable and Runnable interfaces?",
    answerFiles: ["16Jan2025.java--what-is-the-difference-between-callable-and-runnable-interfaces.md"],
  },
  {
    sectionId: "section_3",
    subSectionId: "sub_sec_3_5",
    id: "ques_3_5_2",
    name: "How do you ensure thread safety in a multithreaded Java application?",
    answerFiles: ["16Jan2025.java--how-do-you-ensure-thread-safety-in-a-multithreaded-java-application.md"],
  },
  {
    sectionId: "section_4",
    subSectionId: "sub_sec_4_1",
    id: "ques_4_1_1",
    name: "Compare microservices and monolithic architectures with examples.",
    answerFiles: ["16Jan2025.java--compare-microservices-and-monolithic-architectures-with-examples.md"],
  },
  {
    sectionId: "section_4",
    subSectionId: "sub_sec_4_1",
    id: "ques_4_1_2",
    name: "How does Spring Boot enable service registration and discovery in a microservices architecture?",
    answerFiles: [
      "16Jan2025.java--how-does-spring-boot-enable-service-registration-and-discovery-in-a-microservices-architecture.md",
    ],
  },
  {
    sectionId: "section_4",
    subSectionId: "sub_sec_4_2",
    id: "ques_4_2_1",
    name: "Compare RestTemplate and WebClient for consuming REST APIs.",
    answerFiles: ["16Jan2025.java--compare-resttemplate-and-webclient-for-consuming-rest-apis.md"],
  },
  {
    sectionId: "section_4",
    subSectionId: "sub_sec_4_2",
    id: "ques_4_2_2",
    name: "How would you implement a circuit breaker in a Spring Boot microservices application?",
    answerFiles: [
      "16Jan2025.java--how-would-you-implement-a-circuit-breaker-in-a-spring-boot-microservices-application.md",
    ],
  },
  {
    sectionId: "section_4",
    subSectionId: "sub_sec_4_3",
    id: "ques_4_3_1",
    name: "How do you secure microservices using OAuth2 and Spring Security?",
    answerFiles: ["16Jan2025.java--how-do-you-secure-microservices-using-oauth2-and-spring-security.md"],
  },
  {
    sectionId: "section_4",
    subSectionId: "sub_sec_4_4",
    id: "ques_4_4_1",
    name: "Explain how to handle instance failures in microservices using retries or circuit breakers.",
    answerFiles: [
      "16Jan2025.java--explain-how-to-handle-instance-failures-in-microservices-using-retries-or-circuit-breakers.md",
    ],
  },
  {
    sectionId: "section_5",
    subSectionId: "sub_sec_5_1",
    id: "ques_5_1_1",
    name: "How would you programmatically upload a file to an S3 bucket using AWS SDK?",
    answerFiles: [
      "16Jan2025.aws-cloud--how-would-you-programmatically-upload-a-file-to-an-s3-bucket-using-aws-sdk.md",
    ],
  },
  {
    sectionId: "section_5",
    subSectionId: "sub_sec_5_1",
    id: "ques_5_1_2",
    name: "What are the key steps to manage an RDS database in AWS?",
    answerFiles: ["16Jan2025.aws-cloud--what-are-the-key-steps-to-manage-an-rds-database-in-aws.md"],
  },
  {
    sectionId: "section_5",
    subSectionId: "sub_sec_5_2",
    id: "ques_5_2_1",
    name: "What are the key steps for manually deploying a Java application?",
    answerFiles: ["16Jan2025.aws-cloud--what-are-the-key-steps-for-manually-deploying-a-java-application.md"],
  },
  {
    sectionId: "section_5",
    subSectionId: "sub_sec_5_2",
    id: "ques_5_2_2",
    name: "How would you configure a CI/CD pipeline using Jenkins for automated deployments?",
    answerFiles: [
      "16Jan2025.aws-cloud--how-would-you-configure-a-ci-and-cd-pipeline-using-jenkins-for-automated-deployments.md",
    ],
  },
  {
    sectionId: "section_5",
    subSectionId: "sub_sec_5_3",
    id: "ques_5_3_1",
    name: "What is Docker, and how does it ensure consistent deployments?",
    answerFiles: ["16Jan2025.aws-cloud--what-is-docker-and-how-does-it-ensure-consistent-deployments.md"],
  },
  {
    sectionId: "section_5",
    subSectionId: "sub_sec_5_3",
    id: "ques_5_3_2",
    name: "Explain the purpose of Kubernetes configuration files in application deployment.",
    answerFiles: [
      "16Jan2025.aws-cloud--explain-the-purpose-of-kubernetes-configuration-files-in-application-deployment.md",
    ],
  },
  {
    sectionId: "section_6",
    subSectionId: "sub_sec_6_1",
    id: "ques_6_1_1",
    name: "Provide an example of using the Singleton pattern in Java.",
    answerFiles: ["16Jan2025.design-patterns--provide-an-example-of-using-the-singleton-pattern-in-java.md"],
  },
  {
    sectionId: "section_6",
    subSectionId: "sub_sec_6_1",
    id: "ques_6_1_2",
    name: "What are the key benefits of using the Factory pattern in enterprise applications?",
    answerFiles: [
      "16Jan2025.design-patterns--what-are-the-key-benefits-of-using-the-factory-pattern-in-enterprise-applications.md",
    ],
  },
  {
    sectionId: "section_6",
    subSectionId: "sub_sec_6_2",
    id: "ques_6_2_1",
    name: "How do you handle concurrency in large-scale applications?",
    answerFiles: [
      "16Jan2025.enterprise-application-development--how-do-you-handle-concurrency-in-largescale-applications.md",
    ],
  },
  {
    sectionId: "section_6",
    subSectionId: "sub_sec_6_2",
    id: "ques_6_2_2",
    name: "Why is immutability important in Java? Provide a practical example.",
    answerFiles: [
      "16Jan2025.enterprise-application-development--why-is-immutability-important-in-java-provide-a-practical-example.md",
    ],
  },
  {
    sectionId: "section_7",
    subSectionId: "sub_sec_7_1",
    id: "ques_7_1_1",
    name: "What is the role of JMX in monitoring Java applications?",
    answerFiles: [
      "16Jan2025.miscellaneous--jmx-n-mxbeans--what-is-the-role-of-jmx-in-monitoring-java-applications.md",
    ],
  },
  {
    sectionId: "section_7",
    subSectionId: "sub_sec_7_2",
    id: "ques_7_2_1",
    name: "Compare Statement, PreparedStatement, and CallableStatement with examples.",
    answerFiles: [
      "16Jan2025.miscellaneous--drivermanager--compare-statement-preparedstatement-and-callablestatement-with-examples.md",
    ],
  },
  {
    sectionId: "section_7",
    subSectionId: "sub_sec_7_3",
    id: "ques_7_3_1",
    name: "How would you troubleshoot and handle failures in a Kafka messaging system?",
    answerFiles: [
      "16Jan2025.miscellaneous--kafka-messaging--how-would-you-troubleshoot-and-handle-failures-in-a-kafka-messaging-system.md",
    ],
  },
];

const questionData1 = [
  {
    sectionId: "section_8",
    subSectionId: "sub_sec_8_1",
    id: "ques_8_1_1",
    name: "What are variables?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_8",
    subSectionId: "sub_sec_8_1",
    id: "ques_8_1_2",
    name: "What are data types in JavaScript?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_8",
    subSectionId: "sub_sec_8_2",
    id: "ques_8_2_1",
    name: "What is an if-else statement?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_8",
    subSectionId: "sub_sec_8_2",
    id: "ques_8_2_2",
    name: "How do loops work in JavaScript?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_9",
    subSectionId: "sub_sec_9_1",
    id: "ques_9_1_1",
    name: "What is a class?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_9",
    subSectionId: "sub_sec_9_1",
    id: "ques_9_1_2",
    name: "How do you create an object in JavaScript?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_9",
    subSectionId: "sub_sec_9_2",
    id: "ques_9_2_1",
    name: "What is inheritance?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_9",
    subSectionId: "sub_sec_9_2",
    id: "ques_9_2_2",
    name: "How do you use inheritance in JavaScript?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_10",
    subSectionId: "sub_sec_10_1",
    id: "ques_10_1_1",
    name: "What are promises in JavaScript?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_10",
    subSectionId: "sub_sec_10_1",
    id: "ques_10_1_2",
    name: "How do you handle errors in promises?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_10",
    subSectionId: "sub_sec_10_2",
    id: "ques_10_2_1",
    name: "What is async/await?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_10",
    subSectionId: "sub_sec_10_2",
    id: "ques_10_2_2",
    name: "How does async/await simplify asynchronous programming?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_1",
    id: "ques_12_1_1",
    name: "How would you implement the Singleton Pattern in a thread-safe manner using Java 8 features?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_1",
    id: "ques_12_1_2",
    name: "Can you explain the Factory Pattern and provide an example of its implementation in the ShubhWeb project?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_1",
    id: "ques_12_1_3",
    name: "Describe the Abstract Factory Pattern and how it can be used in integrating multiple database systems.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_1",
    id: "ques_12_1_4",
    name: "What are the advantages of the Builder Pattern when constructing complex objects like REST API responses?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_1",
    id: "ques_12_1_5",
    name: "Provide a real-world use case of the Prototype Pattern in a microservices architecture.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_1",
    id: "ques_12_1_6",
    name: "Explain how the Adapter Pattern helped you integrate third-party APIs in your projects.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_1",
    id: "ques_12_1_7",
    name: "Discuss the Bridge Pattern and how it can decouple abstraction from implementation in a modular system.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_1",
    id: "ques_12_1_8",
    name: "How would you use the Composite Pattern to represent a hierarchical menu in a ReactJS application?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_1",
    id: "ques_12_1_9",
    name: "Explain the Decorator Pattern and its application in extending the functionality of a logging service.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_1",
    id: "ques_12_1_10",
    name: "How does the Proxy Pattern differ from the Decorator Pattern? Provide examples from your experience.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_1",
    id: "ques_12_1_11",
    name: "Describe the Chain of Responsibility Pattern and how it could be used in implementing middleware in a Spring Boot application.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_1",
    id: "ques_12_1_12",
    name: "Explain how you have utilized the Observer Pattern to notify dependent microservices of state changes.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_1",
    id: "ques_12_1_13",
    name: "Provide an example of the Command Pattern in automating build tasks using Jenkins.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_1",
    id: "ques_12_1_14",
    name: "How would you use the State Pattern in managing a user authentication flow?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_1",
    id: "ques_12_1_15",
    name: "Discuss the Strategy Pattern and its role in handling multiple payment gateways.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_2",
    id: "ques_12_2_1",
    name: "What is MVC Pattern, and how have you implemented it in the ESG Lythouse application?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_2",
    id: "ques_12_2_2",
    name: "Explain the Repository Pattern and its advantages in managing database operations.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_2",
    id: "ques_12_2_3",
    name: "How would you implement the DAO Pattern to separate persistence logic in a Spring Boot project?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_2",
    id: "ques_12_2_4",
    name: "Describe the Service Locator Pattern and its role in managing dependencies.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_2",
    id: "ques_12_2_5",
    name: "How have you used the Active Record Pattern for ORM in your past projects?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_2",
    id: "ques_12_2_6",
    name: "Explain the Lazy Loading Pattern and its benefits in optimizing application performance.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_2",
    id: "ques_12_2_7",
    name: "What is the Intercepting Filter Pattern, and how would you use it in request pre-processing?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_2",
    id: "ques_12_2_8",
    name: "Discuss the Template Method Pattern with an example of implementing shared workflows.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_2",
    id: "ques_12_2_9",
    name: "How have you implemented the Dependency Injection Pattern in your microservices projects?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_2",
    id: "ques_12_2_10",
    name: "Provide a use case for the Event Aggregator Pattern in event-driven architecture.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_2",
    id: "ques_12_2_11",
    name: "Explain the Business Delegate Pattern and its use in managing service lookups.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_2",
    id: "ques_12_2_12",
    name: "How would you use the Observer Pattern to implement a notification system in a ReactJS app?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_2",
    id: "ques_12_2_13",
    name: "Describe the Façade Pattern and its role in simplifying complex system interactions.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_2",
    id: "ques_12_2_14",
    name: "Explain the CQRS Pattern and its advantages in separating read and write operations.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_2",
    id: "ques_12_2_15",
    name: "How have you used the Strangler Fig Pattern to migrate a monolithic application to microservices?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_3",
    id: "ques_12_3_1",
    name: "How would you design a system to migrate data from legacy databases to MongoDB using Spring Batch?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_3",
    id: "ques_12_3_2",
    name: "Can you describe your approach to implementing JWT-based authentication in a Spring Boot REST API?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_3",
    id: "ques_12_3_3",
    name: "How would you use the Observer Pattern to notify microservices of data changes in an event-driven system?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_3",
    id: "ques_12_3_4",
    name: "Discuss how you would design a scalable logging solution using the Decorator Pattern.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_3",
    id: "ques_12_3_5",
    name: "What steps would you take to implement the Circuit Breaker Pattern in a microservices architecture to handle service failures?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_3",
    id: "ques_12_3_6",
    name: "How would you optimize an AWS-hosted application using EC2, Lambda, and S3?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_3",
    id: "ques_12_3_7",
    name: "Describe your approach to implementing GraphQL queries in the ESG Lythouse application.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_3",
    id: "ques_12_3_8",
    name: "How would you implement a custom Factory Pattern to manage DAO objects in a Spring Boot project?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_3",
    id: "ques_12_3_9",
    name: "Explain your approach to integrating ReactJS with Spring Boot for building scalable applications.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_3",
    id: "ques_12_3_10",
    name: "How would you design a Jenkins pipeline for automating builds and deployments for a microservices project?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_3",
    id: "ques_12_3_11",
    name: "Provide a detailed example of using the Builder Pattern to construct complex API responses.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_3",
    id: "ques_12_3_12",
    name: "How would you implement a Strangler Fig Pattern to migrate ShubhWeb from monolith to microservices?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_3",
    id: "ques_12_3_13",
    name: "Explain how you handled distributed transactions in your projects involving RDBMS and MongoDB.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_3",
    id: "ques_12_3_14",
    name: "How would you implement the State Pattern to manage session state in a Spring Boot application?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_3",
    id: "ques_12_3_15",
    name: "Describe your approach to implementing a real-time notification system using Kafka or RabbitMQ.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_3",
    id: "ques_12_3_16",
    name: "How do you ensure data consistency when working with distributed systems in an event-driven architecture?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_3",
    id: "ques_12_3_17",
    name: "What steps would you take to implement SAGA in managing distributed transactions?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_3",
    id: "ques_12_3_18",
    name: "Explain how you would optimize a microservices architecture for handling large volumes of requests.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_3",
    id: "ques_12_3_19",
    name: "How would you design a load-balancing solution for a Spring Boot application using AWS ELB?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_3",
    id: "ques_12_3_20",
    name: "Describe your experience implementing security best practices in DevOps pipelines using Docker and Kubernetes.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_4",
    id: "ques_12_4_1",
    name: "What is the Factory Pattern, and how does it simplify object creation in Spring Boot applications?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_4",
    id: "ques_12_4_2",
    name: "How would you implement a Factory Pattern to manage multiple payment gateways in an e-commerce application?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_4",
    id: "ques_12_4_3",
    name: "Can you design a Factory Pattern to handle different types of notifications (email, SMS, push)?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_4",
    id: "ques_12_4_4",
    name: "Discuss the use of Factory Pattern in creating DAO objects for various databases.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_4",
    id: "ques_12_4_5",
    name: "How can you use the Factory Pattern to abstract third-party API integrations?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_4",
    id: "ques_12_4_6",
    name: "Provide a real-world example of Factory Pattern implementation from your past projects.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_4",
    id: "ques_12_4_7",
    name: "How would you ensure thread safety in a Factory Pattern implementation?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_4",
    id: "ques_12_4_8",
    name: "Can the Factory Pattern be combined with Dependency Injection? Explain.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_4",
    id: "ques_12_4_9",
    name: "How would you use the Factory Pattern to handle object creation based on user roles?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_4",
    id: "ques_12_4_10",
    name: "Explain how Factory Pattern supports Open/Closed Principle with examples.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_5",
    id: "ques_12_5_1",
    name: "What are the advantages of the Builder Pattern over telescoping constructors in Java?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_5",
    id: "ques_12_5_2",
    name: "How would you use the Builder Pattern to construct complex JSON responses?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_5",
    id: "ques_12_5_3",
    name: "Provide a use case for the Builder Pattern in your microservices experience.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_5",
    id: "ques_12_5_4",
    name: "How would you implement the Builder Pattern for constructing immutable objects?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_5",
    id: "ques_12_5_5",
    name: "Discuss a scenario where the Builder Pattern improved code readability and maintainability.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_5",
    id: "ques_12_5_6",
    name: "How can you use the Builder Pattern in creating dynamic SQL queries?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_5",
    id: "ques_12_5_7",
    name: "Explain the difference between the Factory Pattern and Builder Pattern with examples.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_5",
    id: "ques_12_5_8",
    name: "How would you implement a Builder Pattern to handle optional fields in an object?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_5",
    id: "ques_12_5_9",
    name: "Describe the use of Builder Pattern in constructing REST API requests in Spring Boot.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_5",
    id: "ques_12_5_10",
    name: "How can the Builder Pattern be used in chainable method calls?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_1",
    name: "Explain the differences between Spring Boot JPA and MyBatis. When would you use each?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_2",
    name: "How would you configure and monitor a Jenkins pipeline for microservices deployment?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_3",
    name: "How have you handled data consistency in systems using RDBMS and MongoDB?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_4",
    name: "Explain your approach to implementing JWT-based authentication in a REST API.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_5",
    name: "Describe how you optimized a Spring Boot application for performance in a high-load environment.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_6",
    name: "How would you design a Circuit Breaker for inter-service communication in microservices?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_7",
    name: "Explain how you used AWS Lambda for serverless data processing.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_8",
    name: "What steps would you take to migrate a monolithic application to microservices?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_9",
    name: "How do you manage session state in a ReactJS and Spring Boot integrated application?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_10",
    name: "Discuss your approach to implementing data migration using Java concurrent API.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_11",
    name: "How would you configure Docker and Kubernetes for a multi-environment deployment pipeline?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_12",
    name: "What are the trade-offs between using Saga Pattern and Two-Phase Commit for distributed transactions?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_13",
    name: "Explain how you would implement an Event-Driven Architecture for real-time data processing.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_14",
    name: "How do you ensure scalability and fault tolerance in an AWS-hosted application?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_15",
    name: "Provide a scenario where you used Builder Pattern for creating modular services.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_16",
    name: "Explain how you have implemented security layers in microservices using Spring Security.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_17",
    name: "How would you use Adapter Pattern to integrate legacy APIs into a new system?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_18",
    name: "What strategies would you employ to optimize a ReactJS application for performance?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_19",
    name: "Discuss how GraphQL differs from REST and your experience implementing it.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_20",
    name: "Explain the role of ANT in automating builds and its advantages over Maven.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_21",
    name: "How have you implemented Observer Pattern to notify services of state changes in real time?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_22",
    name: "Describe your approach to handling distributed logging in a microservices-based application.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_23",
    name: "How would you implement a stateful service in a stateless microservices architecture?",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_24",
    name: "Discuss how Facade Pattern simplifies interactions with complex systems.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_6",
    id: "ques_12_6_25",
    name: "Explain how JPA Criteria API can be used for dynamic query building.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_7",
    id: "ques_12_7_1",
    name: "Question: Write a Java program to remove duplicates from an array.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_7",
    id: "ques_12_7_2",
    name: "Question: Write a Java program to find the second largest element in an array.",
    answers: [],
    answerFiles: [],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_7",
    id: "ques_12_7_3",
    name: "Question: Write a Java program to demonstrate the use of ArrayList and LinkedList.",
    answers: [],
    answerFiles: ["17Jan2025.java--programs--demonstration-of-the-use-the-of-arraylist-and-linkedlist.md"],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_7",
    id: "ques_12_7_4",
    name: "Question: Write a program to demonstrate polymorphism in Java.",
    answers: [],
    answerFiles: ["17Jan2025.java--programs--to-demonstrate-polymorphism-in-java.md"],
  },
  {
    sectionId: "section_12",
    subSectionId: "sub_sec_12_7",
    id: "ques_12_7_5",
    name: "Design a Spring Boot application as per description",
    answers: [],
    answerFiles: [],
  },
];

const questionData = [...questionData0, ...questionData1];

const questionDataLength = questionData.length;
const getQuestionDetailsById = (quesId) => {
  // console.log("quesId: ", quesId);
  const selectedIndex = questionData.findIndex(({ id }) => id === quesId);
  const data = questionData[selectedIndex] || null;
  const nextPrev = calculateNextPrev(questionDataLength, selectedIndex);

  return {
    data: { ...data, answers: data?.answers || [], answerFiles: data?.answerFiles || [] },
    selectedIndex,
    nextId: questionData[nextPrev.next]?.id || null,
    prevId: questionData[nextPrev.prev]?.id || null,
  };
};

export { getQuestionDetailsById };
