spring.application.name=builder-pattern-demo
server.port=8080

# Logging
logging.level.com.p.builder=DEBUG
logging.level.org.springframework.web=INFO

# Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

