apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: todo-platform
type: Opaque
stringData:
  AUTH_DB_USERNAME: root
  AUTH_DB_PASSWORD: root
  TODO_DB_USERNAME: root
  TODO_DB_PASSWORD: root
  JWT_SECRET: change-this-secret-key-to-at-least-32-characters-long
